# Generated by Django 4.1.1 on 2022-09-07 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_newuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='is_admin',
        ),
    ]
