# Generated by Django 4.1.1 on 2022-09-07 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('animal_group', models.CharField(choices=[('mammal', 'Mammal'), ('bird', 'Bird'), ('fish', 'Fish'), ('reptile', 'Reptile'), ('amphibian', 'Amphibian'), ('other', 'Other')], max_length=100)),
                ('animal_kind', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, help_text='<em>YYYY-MM-DD</em>', null=True, verbose_name='DOB')),
                ('gotcha_date', models.DateField(help_text='<em>YYYY-MM-DD</em>')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('vet', models.CharField(blank=True, max_length=100)),
                ('appt_date', models.DateField(blank=True, help_text='<em>YYYY-MM-DD</em>', null=True)),
                ('visit_reason', models.CharField(blank=True, max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='pettracker.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(blank=True, help_text='<em>YYYY-MM-DD</em>')),
                ('description', models.TextField(blank=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='pettracker.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('vet', 'Vet'), ('food', 'Food'), ('toys', 'Toys'), ('apparel', 'Apparel'), ('medical', 'Medical'), ('other', 'Other')], max_length=100)),
                ('date', models.DateField(blank=True, help_text='<em>YYYY-MM-DD</em>', null=True)),
                ('amount', models.FloatField(help_text='<em>Currency in USD</em>')),
                ('description', models.TextField(blank=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='pettracker.pet')),
            ],
        ),
    ]
