# Generated by Django 4.1 on 2022-09-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.FloatField(help_text='<em>Currency in USD</em>'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(blank=True, help_text='<em>YYYY-MM-DD</em>'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='date',
            field=models.DateField(blank=True, help_text='<em>YYYY-MM-DD</em>'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='dob',
            field=models.DateField(blank=True, help_text='<em>YYYY-MM-DD</em>', verbose_name='DOB'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gotcha_date',
            field=models.DateField(help_text='<em>YYYY-MM-DD</em>'),
        ),
        migrations.AlterField(
            model_name='record',
            name='appt_date',
            field=models.DateField(blank=True, help_text='<em>YYYY-MM-DD</em>'),
        ),
        migrations.AlterField(
            model_name='record',
            name='clinic_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='vet',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='visit_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
