# Generated by Django 4.1 on 2022-09-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettracker', '0002_alter_expense_amount_alter_expense_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(blank=True, help_text='<em>YYYY-MM-DD</em>', null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='dob',
            field=models.DateField(blank=True, help_text='<em>YYYY-MM-DD</em>', null=True, verbose_name='DOB'),
        ),
        migrations.AlterField(
            model_name='record',
            name='appt_date',
            field=models.DateField(blank=True, help_text='<em>YYYY-MM-DD</em>', null=True),
        ),
    ]
